### ISSUE TITLE
java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by osum54** [TheMrJezza/HorseTpWithMe#3]
[17:38:53 ERROR]: Could not pass event EntityDismountEvent to HorseTpWithMe v7.2.0.0
java.lang.NullPointerException: null
        at com.jbouchier.spigot.htwm.listener.SpigotListener.onEntityDismount(SpigotListener.java:22) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor105.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.1.jar:git-Paper-44]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.1.jar:git-Paper-44]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-44]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-44]
        at net.minecraft.server.v1_16_R1.Entity.removePassenger(Entity.java:2140) ~[patched_1.16.1.jar:git-Paper-44]
        at net.minecraft.server.v1_16_R1.Entity.stopRiding(Entity.java:2055) ~[patched_1.16.1.jar:git-Paper-44]
        at net.minecraft.server.v1_16_R1.EntityLiving.stopRiding(EntityLiving.java:2919) ~[patched_1.16.1.jar:git-Paper-44]
        at net.minecraft.server.v1_16_R1.EntityHuman.stopRiding(EntityHuman.java:949) ~[patched_1.16.1.jar:git-Paper-44]
        at net.minecraft.server.v1_16_R1.EntityPlayer.stopRiding(EntityPlayer.java:1226) ~[patched_1.16.1.jar:git-Paper-44]
        at net.minecraft.server.v1_16_R1.EntityPlayer.stopRiding(EntityPlayer.java:1221) ~[patched_1.16.1.jar:git-Paper-44]
        at net.minecraft.server.v1_16_R1.EntityHuman.passengerTick(EntityHuman.java:367) ~[patched_1.16.1.jar:git-Paper-44]
        at net.minecraft.server.v1_16_R1.WorldServer.a(WorldServer.java:868) ~[patched_1.16.1.jar:git-Paper-44]
        at net.minecraft.server.v1_16_R1.WorldServer.entityJoinedWorld(WorldServer.java:844) ~[patched_1.16.1.jar:git-Paper-44]
        at net.minecraft.server.v1_16_R1.World.a(World.java:932) ~[patched_1.16.1.jar:git-Paper-44]
        at net.minecraft.server.v1_16_R1.WorldServer.doTick(WorldServer.java:526) ~[patched_1.16.1.jar:git-Paper-44]
        at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1353) ~[patched_1.16.1.jar:git-Paper-44]
        at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.1.jar:git-Paper-44]
        at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212) ~[patched_1.16.1.jar:git-Paper-44]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000) ~[patched_1.16.1.jar:git-Paper-44]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-44]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]

**Comment by TheMrJezza** [comment]
Fixed in version 7.3.0.0
